config/routes.rb
Rails.application.routes.draw do

  get 'errors/not_found'

  get 'errors/internal_server_error'

  devise_for :users, :controllers => {registrations: 'registrations'}

  resources :trips
  root 'trips#index', as: 'home'
  post 'trips/:id', :to => "trips#create_day"
  put 'day', :to => "days#update", :as => "update_day"
  delete 'day', :to => "days#destroy", :as => "delete_day"

  resources :places
end

app/models/trip.rb
class Trip < ApplicationRecord
  belongs_to :user, foreign_key: :user_id
  has_many :days
  has_many :places, through: :days
  ########################################
	validates :name,      presence: true
	validates :beginning, presence: true
	validates :duration,  presence: true
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  before_action :set_trip, only: [:show, :edit, :update, :destroy]

  # GET /trips
  # GET /trips.json
  def index
    @trips = Trip.where(user: current_user)
    @trip = Trip.new
  end

  # GET /trips/1
  # GET /trips/1.json
  def show
    @trip = Trip.find(params[:id])
    @days = @trip.days.all
    @places = Array.new(@days.size) { |i| @days[i].places.all }
    @day = Day.new
    @user = current_user
  end

  # GET /trips/new
  def new
    @trip = Trip.new
  end

  # GET /trips/1/edit
  def edit
  end

  # POST /trips
  # POST /trips.json
  def create
    @trip = Trip.new({"name" => "New Trip",
                      "beginning" => Time.now.strftime("%d/%m/%Y"),
                      "duration" => "0",
                      "user" => current_user})

    respond_to do |format|
      if @trip.save
        format.html { redirect_to @trip, notice: 'Trip was successfully created.' }
        format.json { render :show, status: :created, location: @trip }
      else
        format.html { render home_path }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  # POST /trips/1
  # POST /trips/1.json
  def create_day
    trip = Trip.find(params[:id])
    offset = 0
    trip.days.all.each do |day|
        offset += 1
    end
    @day = Day.new({"date" => trip.beginning + offset , "trip" => trip})
    trip.update_attribute(:duration, trip.attributes['duration'] + 1)
    trip.save
    respond_to do |format|
      if @day.save
        format.html { redirect_to trip, notice: 'Day was successfully created.' }
        format.json { render :show, status: :created, location: @day }
      else
        format.html { render home_path }
        format.json { render json: @day.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trips/1
  # PATCH/PUT /trips/1.json
  def update
    respond_to do |format|
      if @trip.update(trip_params)
        format.html { redirect_to @trip, notice: 'Trip was successfully updated.' }
        format.json { render :show, status: :ok, location: @trip }
        offset = -1
        @trip.days.all.each do |day|
            offset += 1
            day.update_attribute(:date, @trip.beginning + offset)
        end
      else
        format.html { render :edit }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trips/1
  # DELETE /trips/1.json
  def destroy
    @trip.days.all.each do |day|
      day.destroy
    end
    @trip.destroy
    respond_to do |format|
      format.html { redirect_to trips_url, notice: 'Trip was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trip
      @trip = Trip.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def trip_params
      params.require(:trip).permit(:name, :beginning, :duration, :user)
    end
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/trips/index.html.erb
<!--=========================================================================-->
<!--= Trip - Index                                                          =-->
<!--=========================================================================-->
<%= stylesheet_link_tag 'trips' %>

<p class="page-title">My Trips</p>

<div class="trips-container">
  <% @trips.each do |trip| %>
    <%= link_to(trip_path(trip)) do %>
      <div class="trip card">
        <p class="name"><span><%= trip.name %><span/></p>
        <div class="info">
          <p><span>Beginning:</span> <%= trip.beginning.strftime("%d/%m/%Y") %></p>
          <p><span>Duration:</span> <%= trip.duration %> days</p>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

<div class="content">
  <%= form_for(@trip, url: trips_path) do |f| %>
    <% if @trip.errors.any? %>
      <ul>
        <% @trip.errors.full_messages.each do |msg| %>
          <li><% puts "#{msg}" %></li>
        <% end %>
      </ul>
    <% end %>

    <div class="container-add-trip">
      <button id="submit" class="btn">
        <i class="fa fa-5x fa-plus"></i>
        <%= f.submit('', :hidden => true) %>
      </button>
    </div>

  <% end %>
</div>


<!--=========================================================================-->

app/views/trips/show.html.erb
<!--=========================================================================-->
<!--= Trip - Show                                                           =-->
<!--=========================================================================-->
<%= stylesheet_link_tag 'trips' %>

<!--= Trip ==================================================================-->
<p class="page-title">Trip</p>
<div class="btn btn-block delete-trip">
  <%= button_to("Delete", @trip, :method => "delete") %>
</div>
<%= form_for :trip, url: trip_path(@trip), method: :patch do |f| %>
  <div class="trip-info-container">
    <div class="input">
      <%= f.label(:name) %><br>
      <%= f.text_field(:name, :class=>'form-control') %>
    </div>
    <div class="input">
      <%= f.label(:beginning) %><br>
      <%= f.text_field(:beginning, type:'date', :class=>'form-control') %>
    </div>
    <div class="input last">
      <%= f.label(:duration, :class=>"disabled") %><br>
      <%= f.text_field(:duration, :class=>'form-control', disabled: true) %>
    </div>
  </div>
  <div>
  <button class="btn btn-block save-trip">
    <%= f.submit("Save") %>
  </button>
<% end %>

<!--= Locals ================================================================-->
<!-- <p class="page-title">Locals</p>
<div class="locals-container card">
  <div class="local">
    <%= image_tag('place.svg') %>
    <p><span>Paris</span></p>
  </div>

  <div class="local">
    <%= image_tag('place.svg') %>
    <p><span>London</span></p>
  </div>
</div> -->

<!--= Itinerary ============================================================-->
<p class="page-title">Itinerary</p>
<div id="scroll-top-container">
  <div id="scroll-top"></div>
</div>
<div id="itinerary-container">

  <% @days.each_with_index do |day, i| %>
    <div class="day card">
      <div class="day-header">
        <p><%= "#{i+1} - #{day.date.strftime('%d/%m/%Y')}" %></p>
        <%= form_for :day, url: delete_day_path(:day), method: :delete do |f| %>
          <%= hidden_field(:day, :selday, :value => day.id) %>
          <div class="btn btn-delete-day">
            <%= submit_tag('X') %>
          </div>
        <% end %>
      </div>
      <% @places[i].size.times do |j| %>
        <div class="place">
          <div class="row">
            <div class="col">
              <%= image_tag(@places[i][j].img) %>
            </div>
            <div class="col">
              <p><span><%= @places[i][j].name %></span></p>
              <p><%= @places[i][j].openinghours %></p>
              <p><%= @places[i][j].price %></p>
            </div>
          </div>
        </div>
      <% end %>
      <div class="container-add-place">
        <%= form_for :user, url: user_registration_path(current_user), method: :put do |f| %>
          <%= hidden_field(:user, :selday, :value => day.id) %>
          <button class="btn" data-toggle="modal" data-target="#modal">
            <i class="fa fa-5x fa-plus"></i>
            <%= f.submit('', :hidden => true) %>
          </button>
        <% end %>
      </div>
    </div>
  <% end %>

  <div class="container-add-day">
    <%= form_for(@day, url: trip_path) do |f| %>
      <button class="btn">
        <i class="fa fa-5x fa-plus"></i>
        <%= f.submit('', :hidden => true) %>
      </button>
    <% end %>
  </div>
</div>

<!--=========================================================================-->
<script>
setInterval(function loop() {
  $("#scroll-top").width(291*($("#itinerary-container").children().length-1)+41);
  return loop;
}(), 1000);
$("#scroll-top-container").scroll(function(){
  $("#itinerary-container").scrollLeft($("#scroll-top-container").scrollLeft());
});
$("#itinerary-container").scroll(function(){
  $("#scroll-top-container").scrollLeft($("#itinerary-container").scrollLeft());
});
</script>

<!--=========================================================================-->