config/routes.rb
Rails.application.routes.draw do

  get 'errors/not_found'

  get 'errors/internal_server_error'

  devise_for :users, :controllers => {registrations: 'registrations'}

  resources :trips
  root 'trips#index', as: 'home'
  post 'trips/:id', :to => "trips#create_day"
  put 'day', :to => "days#update", :as => "update_day"
  delete 'day', :to => "days#destroy", :as => "delete_day"

  resources :places
end

app/models/day.rb
class Day < ApplicationRecord
  belongs_to :trip, foreign_key: :trip_id
  has_and_belongs_to_many :places
  ########################################
  validates :date, presence: true
end

app/views/layouts/elements/_drawer.html.erb
<!--=========================================================================-->
<!--= Drawer                                                                =-->
<!--=========================================================================-->
<div class="mdl-layout__drawer">
  <header class="drawer-header">
    <button type="button" class="btn" data-toggle="modal" data-target="#modalimage">
      <% if current_user.img == nil or current_user.img == '' %>
        <% current_user.update_attribute(:img, "user.svg") %>
      <% end %>
      <%= image_tag(current_user.img, :class=>"drawer-image", :id=>'user-img') %>
    </button>
    <%= content_tag(:p, current_user.name)%>
  </header>
  <nav class="mdl-navigation">
    <!-- My Trips -->
    <%= link_to home_path, class: 'mdl-navigation__link' + (if controller.controller_name == "trips" then " active" else "" end) do %>
      <i class="material-icons">map</i>My Trips
    <% end %>

    <!-- Exit -->
    <%= link_to(destroy_user_session_path, class: "mdl-navigation__link") do %>
      <i class="material-icons">exit_to_app</i>Exit
    <% end %>
  </nav>
</div>

<!--=========================================================================-->
<div id="modalimage" class="modal fade" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <%= form_for :user, url: user_registration_path(current_user), method: :put do |f| %>
        <div class="modal-header">
          <h5 class="modal-title">Change your Image</h5>
        </div>
        <div class="modal-body">
          <div class="change-img-container">
            <div class="input">
              <%= f.label("Image URL") %><br>
              <%= f.text_field(:img, :class=>'form-control', :id=>'user-img-url') %>
            </div>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-modal cancel-img-btn" data-dismiss="modal">CANCEL</button>
          <div class="btn btn-modal save-img-btn">
            <%= f.submit("Save", :id=>'save-user-img') %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

<!--=========================================================================-->
<script>
$('#save-user-img').click(function() {
  $('#user-img').attr('src', $('#user-img-url').val());
  $('#modalimage').modal('hide');
});
</script>

<!--=========================================================================-->

app/views/layouts/elements/_footer.html.erb
<!--=========================================================================-->
<!--= Footer                                                                =-->
<!--=========================================================================-->
<footer class="page-footer elegant-color text-center">
  <div class="footer-copyright text-center">
    <a href="#">Rotalize</a> <%= Date.current.year %>
  </div>
</footer>

<!--=========================================================================-->

app/views/layouts/elements/_header.html.erb
<!--=========================================================================-->
<!--= Header                                                                =-->
<!--=========================================================================-->
<header class="mdl-layout__header">
  <div class="mdl-layout__header-row">
    <%= image_tag('logo/logo_white.svg', :class=>"logo-image") %>
    <h1 class="header-title">Rotalize</h1>
  </div>
</header>

<!--=========================================================================-->

app/views/layouts/elements/_modal.html.erb
<!--=========================================================================-->
<!--= Modal                                                                 =-->
<!--=========================================================================-->

<div id="modal" class="modal fade" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Add Place</h5>
      </div>
      <%= form_for :day, url: update_day_path(:day), method: :put do |f| %>
        <div class="modal-body">
          <% Local.all.each_with_index do |local, i| %>
            <!-- Local -->
            <div class="modal-local">
              <%= content_tag(:div, "", class: "header waves-light", "data-toggle": "collapse", "data-target": "#collapse#{i}") do %>
                <%= image_tag("place.svg") %>
                <p><%= local.name %></p>
              <% end %>
              <%= content_tag(:div, "", id: "collapse#{i}", class: "collapse show") do %>
                <!-- Lugar -->
                <%= f.collection_check_boxes(:place_ids, local.places.all, :id, :name) do |b| %>
                  <div>
                    <%= b.check_box class: "mdl-checkbox__input" %>
                    <%= b.label class: "mdl-checkbox__label" %>
                  </div>
                <% end %>
              <% end %>
            </div>
          <% end %>
        </div>
        <div class="modal-footer">
          <%= hidden_field(:day, :places, :value => 1) %>
          <button type="button" class="btn btn-modal cancel" data-dismiss="modal">CANCEL</button>
          <button id="done" class="btn btn-modal save-img-btn">DONE</button>
        </div>
        <% end %>
    </div>
  </div>
</div>

<!--=========================================================================-->

<script>
$('#done').click(function() {
    $('form').submit();
    form_submitted = false;
    $("#modal").modal('hide');
});
</script>