config/routes.rb
Rails.application.routes.draw do

  get 'errors/not_found'

  get 'errors/internal_server_error'

  devise_for :users, :controllers => {registrations: 'registrations'}

  resources :trips
  root 'trips#index', as: 'home'
  post 'trips/:id', :to => "trips#create_day"
  put 'day', :to => "days#update", :as => "update_day"
  delete 'day', :to => "days#destroy", :as => "delete_day"

  resources :places
end

app/models/trip.rb
class Trip < ApplicationRecord
  belongs_to :user, foreign_key: :user_id
  has_many :days
  has_many :places, through: :days
  ########################################
	validates :name,      presence: true
	validates :beginning, presence: true
	validates :duration,  presence: true
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  before_action :set_trip, only: [:show, :edit, :update, :destroy]

  # GET /trips
  # GET /trips.json
  def index
    @trips = Trip.where(user: current_user)
    @trip = Trip.new
  end

  # GET /trips/1
  # GET /trips/1.json
  def show
    @trip = Trip.find(params[:id])
    @days = @trip.days.all
    @places = Array.new(@days.size) { |i| @days[i].places.all }
    @day = Day.new
    @user = current_user
  end

  # GET /trips/new
  def new
    @trip = Trip.new
  end

  # GET /trips/1/edit
  def edit
  end

  # POST /trips
  # POST /trips.json
  def create
    @trip = Trip.new({"name" => "New Trip",
                      "beginning" => Time.now.strftime("%d/%m/%Y"),
                      "duration" => "0",
                      "user" => current_user})

    respond_to do |format|
      if @trip.save
        format.html { redirect_to @trip, notice: 'Trip was successfully created.' }
        format.json { render :show, status: :created, location: @trip }
      else
        format.html { render home_path }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  # POST /trips/1
  # POST /trips/1.json
  def create_day
    trip = Trip.find(params[:id])
    offset = 0
    trip.days.all.each do |day|
        offset += 1
    end
    @day = Day.new({"date" => trip.beginning + offset , "trip" => trip})
    trip.update_attribute(:duration, trip.attributes['duration'] + 1)
    trip.save
    respond_to do |format|
      if @day.save
        format.html { redirect_to trip, notice: 'Day was successfully created.' }
        format.json { render :show, status: :created, location: @day }
      else
        format.html { render home_path }
        format.json { render json: @day.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trips/1
  # PATCH/PUT /trips/1.json
  def update
    respond_to do |format|
      if @trip.update(trip_params)
        format.html { redirect_to @trip, notice: 'Trip was successfully updated.' }
        format.json { render :show, status: :ok, location: @trip }
        offset = -1
        @trip.days.all.each do |day|
            offset += 1
            day.update_attribute(:date, @trip.beginning + offset)
        end
      else
        format.html { render :edit }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trips/1
  # DELETE /trips/1.json
  def destroy
    @trip.days.all.each do |day|
      day.destroy
    end
    @trip.destroy
    respond_to do |format|
      format.html { redirect_to trips_url, notice: 'Trip was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trip
      @trip = Trip.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def trip_params
      params.require(:trip).permit(:name, :beginning, :duration, :user)
    end
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/trips/old/_form.html.haml
= form_for @trip do |f|
  - if @trip.errors.any?
    #error_explanation
      %h2= "#{pluralize(@trip.errors.count, "error")} prohibited this trip from being saved:"
      %ul
        - @trip.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :beginning
    = f.date_select :beginning
  .field
    = f.label :duration
    = f.number_field :duration
  .actions
    = f.submit 'Save'

app/views/trips/old/edit.html.haml
%h1 Editing trip

= render 'form'

= link_to 'Show', @trip
\|
= link_to 'Back', trips_path

app/views/trips/old/index.html.erb
<!-- %h1 Apelidos cadastrados
- @trip.each do |ap|
	%p= "#{ap.id}" -->

	<%= render 'layouts/header' %>
	<%= render 'layouts/drawer' %>

	<main class="mdl-layout__content">
		<%= yield %>
	</main>

	<%= render 'layouts/footer' %>

app/views/trips/old/index.html.haml
%h1 Listing trips

%table
  %thead
    %tr
      %th Name
      %th Beginning
      %th Duration
      %th
      %th
      %th

  %tbody
    - @trips.each do |trip|
      %tr
        %td= trip.name
        %td= trip.beginning
        %td= trip.duration
        %td= link_to 'Show', trip
        %td= link_to 'Edit', edit_trip_path(trip)
        %td= link_to 'Destroy', trip, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Trip', new_trip_path

app/views/trips/old/new.html.haml
%h1 New trip

= render 'form'

= link_to 'Back', trips_path

app/views/trips/old/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @trip.name
%p
  %b Beginning:
  = @trip.beginning
%p
  %b Duration:
  = @trip.duration

= link_to 'Edit', edit_trip_path(@trip)
\|
= link_to 'Back', trips_path