config/routes.rb
Rails.application.routes.draw do

  get 'errors/not_found'

  get 'errors/internal_server_error'

  devise_for :users, :controllers => {registrations: 'registrations'}

  resources :trips
  root 'trips#index', as: 'home'
  post 'trips/:id', :to => "trips#create_day"
  put 'day', :to => "days#update", :as => "update_day"
  delete 'day', :to => "days#destroy", :as => "delete_day"

  resources :places
end

app/models/place.rb
class Place < ApplicationRecord
  belongs_to :local, foreign_key: :local_id
  has_and_belongs_to_many :days
  ########################################
  validates :name,         presence: true
  validates :placetype,    presence: true
  # validates :description,  presence: true
  # validates :address,      presence: true
  # validates :openinghours, presence: true
  # validates :price,        presence: true
  # validates :img,          presence: true

  def get_name
    return "#{name}"
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :set_place, only: [:show, :edit, :update, :destroy]

  # GET /places
  # GET /places.json
  def index
    @places = Place.all
  end

  # GET /places/1
  # GET /places/1.json
  def show
  end

  # GET /places/new
  def new
    @place = Place.new
  end

  # GET /places/1/edit
  def edit
  end

  # POST /places
  # POST /places.json
  def create
    @place = Place.new(place_params)

    respond_to do |format|
      if @place.save
        format.html { redirect_to @place, notice: 'Place was successfully created.' }
        format.json { render :show, status: :created, location: @place }
      else
        format.html { render :new }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /places/1
  # PATCH/PUT /places/1.json
  def update
    respond_to do |format|
      if @place.update(place_params)
        format.html { redirect_to @place, notice: 'Place was successfully updated.' }
        format.json { render :show, status: :ok, location: @place }
      else
        format.html { render :edit }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /places/1
  # DELETE /places/1.json
  def destroy
    @place.destroy
    respond_to do |format|
      format.html { redirect_to places_url, notice: 'Place was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_place
      @place = Place.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def place_params
      params.require(:place).permit(:name, :placetype, :opentime, :closetime, :img, :description, :address, :price)
    end
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/places/_form.html.haml
= form_for @place do |f|
  - if @place.errors.any?
    #error_explanation
      %h2= "#{pluralize(@place.errors.count, "error")} prohibited this place from being saved:"
      %ul
        - @place.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :placetype
    = f.number_field :placetype
  .field
    = f.label :opentime
    = f.time_select :opentime
  .field
    = f.label :closetime
    = f.time_select :closetime
  .field
    = f.label :img
    = f.text_field :img
  .field
    = f.label :description
    = f.text_field :description
  .field
    = f.label :address
    = f.text_field :address
  .field
    = f.label :price
    = f.text_field :price
  .actions
    = f.submit 'Save'

app/views/places/edit.html.haml
%h1 Editing place

= render 'form'

= link_to 'Show', @place
\|
= link_to 'Back', places_path

app/views/places/index.html.haml
%h1 Listing places

%table
  %thead
    %tr
      %th Name
      %th Placetype
      %th Opentime
      %th Closetime
      %th Img
      %th Description
      %th Address
      %th Price
      %th
      %th
      %th

  %tbody
    - @places.each do |place|
      %tr
        %td= place.name
        %td= place.placetype
        %td= place.opentime
        %td= place.closetime
        %td= place.img
        %td= place.description
        %td= place.address
        %td= place.price
        %td= link_to 'Show', place
        %td= link_to 'Edit', edit_place_path(place)
        %td= link_to 'Destroy', place, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Place', new_place_path

app/views/places/new.html.haml
%h1 New place

= render 'form'

= link_to 'Back', places_path

app/views/places/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @place.name
%p
  %b Placetype:
  = @place.placetype
%p
  %b Opentime:
  = @place.opentime
%p
  %b Closetime:
  = @place.closetime
%p
  %b Img:
  = @place.img
%p
  %b Description:
  = @place.description
%p
  %b Address:
  = @place.address
%p
  %b Price:
  = @place.price

= link_to 'Edit', edit_place_path(@place)
\|
= link_to 'Back', places_path